DROP INDEX _btree_index_sb_messages__sb_message_id;
ALTER TABLE overrides DROP CONSTRAINT name_unique;
ALTER TABLE posroles DROP CONSTRAINT maxm_gid_unique;
ALTER TABLE sb_messages DROP CONSTRAINT sb_message_id_unique;
CREATE INDEX _hash_index_aschannels__guild_id ON aschannels USING HASH ( ( guild_id ) );
CREATE INDEX _btree_index_guilds__premium_end ON guilds USING BTREE ( ( premium_end ) );
CREATE INDEX _hash_index_members__guild_id ON members USING HASH ( ( guild_id ) );
CREATE INDEX _hash_index_members__autoredeem_enabled ON members USING HASH ( ( autoredeem_enabled ) );
CREATE INDEX _btree_index_members__xp ON members USING BTREE ( ( xp ) );
CREATE UNIQUE INDEX _btree_index_overrides__guild_id_name ON overrides USING BTREE ( ( guild_id ) , ( name ) );
CREATE INDEX _hash_index_overrides__starboard_id ON overrides USING HASH ( ( starboard_id ) );
CREATE INDEX _gin_index_overrides__channel_ids ON overrides USING GIN ( ( channel_ids ) );
CREATE INDEX _btree_index_sb_messages__last_known_star_count ON sb_messages USING BTREE ( ( last_known_star_count ) );
CREATE INDEX _hash_index_sb_messages__starboard_id ON sb_messages USING HASH ( ( starboard_id ) );
CREATE INDEX _hash_index_permroles__guild_id ON permroles USING HASH ( ( guild_id ) );
CREATE UNIQUE INDEX _btree_index_posroles__guild_id_max_members ON posroles USING BTREE ( ( guild_id ) , ( max_members ) );
CREATE INDEX _hash_index_starboards__guild_id ON starboards USING HASH ( ( guild_id ) );
CREATE INDEX _gin_index_starboards__star_emojis ON starboards USING GIN ( ( star_emojis ) );
CREATE INDEX _hash_index_xproles__guild_id ON xproles USING HASH ( ( guild_id ) );
CREATE UNIQUE INDEX _btree_index_sb_messages__sb_message_id ON sb_messages USING BTREE ( ( sb_message_id ) );