[tool.black]
line-length=79
skip-magic-trailing-comma=true

[tool.poetry]
name = "starboard"
version = "0.0.0"
description = ""
authors = ["Circuit"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
aiohttp = "^3.8.1"
cachetools = "^5.0.0"
types-cachetools = "^4.2.9"
hikari-clusters = "^0.1.1"
emoji = "^1.6.3"
types-emoji = "^1.2.7"
hikari = "^2.0.0-alpha.106"
hikari-miru = "^1.0.1"
apgorm = "^1.0.0-beta.4"
hikari-crescent = "^0.1.0-beta.1"

[tool.poetry.dev-dependencies]
black = "^22.1"
isort = "^5.9.3"
mypy = "^0.931"
flake8 = "^4.0.1"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
nox = "^2022.1.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
