SET maintenance_work_mem TO '8 GB';
SET max_parallel_maintenance_workers TO 10;
CREATE INDEX _btree_index_members__guild_id ON members USING BTREE ( ( guild_id ) );
CREATE INDEX _btree_index_members__autoredeem_enabled ON members USING BTREE ( ( autoredeem_enabled ) );
CREATE INDEX _btree_index_members__xp ON members USING BTREE ( ( xp ) );
CREATE UNIQUE INDEX _btree_index_sb_messages__sb_message_id ON sb_messages USING BTREE ( ( sb_message_id ) );
CREATE INDEX _btree_index_sb_messages__last_known_point_count ON sb_messages USING BTREE ( ( last_known_point_count ) );
CREATE INDEX _btree_index_sb_messages__starboard_id ON sb_messages USING BTREE ( ( starboard_id ) );
CREATE INDEX _btree_index_votes__starboard_id ON votes USING BTREE ( ( starboard_id ) );
CREATE INDEX _btree_index_votes__user_id ON votes USING BTREE ( ( user_id ) );
CREATE INDEX _btree_index_votes__message_id ON votes USING BTREE ( ( message_id ) );
CREATE INDEX _btree_index_votes__target_author_id ON votes USING BTREE ( ( target_author_id ) );
CREATE INDEX _btree_index_votes__is_downvote ON votes USING BTREE ( ( is_downvote ) );
ALTER TABLE members ADD CONSTRAINT userid_fk FOREIGN KEY ( user_id ) REFERENCES users ( user_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE members ADD CONSTRAINT guildid_fk FOREIGN KEY ( guild_id ) REFERENCES guilds ( guild_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE messages ADD CONSTRAINT guild_id_fk FOREIGN KEY ( guild_id ) REFERENCES guilds ( guild_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE messages ADD CONSTRAINT author_id_fk FOREIGN KEY ( author_id ) REFERENCES users ( user_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE sb_messages ADD CONSTRAINT message_id_fk FOREIGN KEY ( message_id ) REFERENCES messages ( message_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE sb_messages ADD CONSTRAINT starboard_id_fk FOREIGN KEY ( starboard_id ) REFERENCES starboards ( id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE votes ADD CONSTRAINT message_id_fk FOREIGN KEY ( message_id ) REFERENCES messages ( message_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE votes ADD CONSTRAINT starboard_id_fk FOREIGN KEY ( starboard_id ) REFERENCES starboards ( id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE votes ADD CONSTRAINT user_id_fk FOREIGN KEY ( user_id ) REFERENCES users ( user_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE votes ADD CONSTRAINT target_author_id_fk FOREIGN KEY ( target_author_id ) REFERENCES users ( user_id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;