ALTER TABLE members DROP CONSTRAINT userid_fk;
ALTER TABLE members DROP CONSTRAINT guildid_fk;
ALTER TABLE messages DROP CONSTRAINT guild_id_fk;
ALTER TABLE messages DROP CONSTRAINT author_id_fk;
ALTER TABLE sb_messages DROP CONSTRAINT message_id_fk;
ALTER TABLE sb_messages DROP CONSTRAINT starboard_id_fk;
ALTER TABLE votes DROP CONSTRAINT message_id_fk;
ALTER TABLE votes DROP CONSTRAINT starboard_id_fk;
ALTER TABLE votes DROP CONSTRAINT user_id_fk;
ALTER TABLE votes DROP CONSTRAINT target_author_id_fk;
DROP INDEX _btree_index_members__guild_id;
DROP INDEX _btree_index_members__autoredeem_enabled;
DROP INDEX _btree_index_members__xp;
DROP INDEX _btree_index_sb_messages__sb_message_id;
DROP INDEX _btree_index_sb_messages__last_known_point_count;
DROP INDEX _btree_index_sb_messages__starboard_id;
DROP INDEX _btree_index_votes__starboard_id;
DROP INDEX _btree_index_votes__user_id;
DROP INDEX _btree_index_votes__message_id;
DROP INDEX _btree_index_votes__target_author_id;
DROP INDEX _btree_index_votes__is_downvote;