CREATE TABLE overrides ();
ALTER TABLE overrides ADD COLUMN id SERIAL;
ALTER TABLE overrides ADD COLUMN starboard_id NUMERIC;
ALTER TABLE overrides ADD COLUMN channel_ids NUMERIC[];
ALTER TABLE overrides ADD COLUMN overrides JSON;
ALTER TABLE overrides ALTER COLUMN id SET NOT NULL;
ALTER TABLE overrides ALTER COLUMN starboard_id SET NOT NULL;
ALTER TABLE overrides ALTER COLUMN channel_ids SET NOT NULL;
ALTER TABLE overrides ALTER COLUMN overrides SET NOT NULL;
ALTER TABLE overrides ADD CONSTRAINT _overrides_id_primary_key PRIMARY KEY ( id );